"a2ps",
" a2ps",
" card",
" composeglyphs",
" fixnt",
" fixps",
" ogonkify",
" pdiff",
" psmandup",
" psset",
" texi2dvi4a2ps",
"atomvm",
" AtomVM",
" PackBEAM",
"bftpd",
" bftpd",
"biber",
" termux-install-biber",
"electrum",
" electrum",
" helpdev",
"enscript",
" diffpp",
" enscript",
" mkafmmap",
" over",
" sliceprint",
" states",
"fetchmail",
" fetchmail",
" fetchmailconf",
"gitflow-avh",
" git-flow",
" git-flow-bugfix",
" git-flow-config",
" git-flow-feature",
" git-flow-hotfix",
" git-flow-init",
" git-flow-log",
" git-flow-release",
" git-flow-support",
" git-flow-version",
" gitflow-common",
" gitflow-shFlags",
"guile",
" guild",
" guile",
" guile-config",
" guile-snarf",
" guile-tools",
"guile18",
" guile-config1.8",
" guile-snarf1.8",
" guile-tools1.8",
" guile1.8",
"intltool",
" intltool-extract",
" intltool-merge",
" intltool-prepare",
" intltool-update",
" intltoolize",
"jigdo",
" jigdo-file",
" jigdo-lite",
" jigdo-mirror",
"libburn",
" cdrskin",
"libisoburn",
" osirrox",
" xorrecord",
" xorriso",
" xorriso-dd-target",
" xorrisofs",
"luajit",
" luajit",
"mupdf-tools",
" muraster",
" mutool",
"nmh",
" ali",
" anno",
" burst",
" comp",
" dist",
" flist",
" flists",
" fmttest",
" fnext",
" folder",
" folders",
" forw",
" fprev",
" inc",
" install-mh",
" mark",
" mhbuild",
" mhfixmsg",
" mhical",
" mhlist",
" mhlogin",
" mhmail",
" mhn",
" mhparam",
" mhpath",
" mhshow",
" mhstore",
" msgchk",
" new",
" next",
" packf",
" pick",
" prev",
" prompter",
" refile",
" repl",
" rmf",
" rmm",
" scan",
" send",
" sendfiles",
" show",
" sortm",
" unseen",
" whatnow",
" whom",
"pandoc",
" pandoc",
"qemu-system-aarch64-headless",
" qemu-system-aarch64",
"qemu-system-arm-headless",
" qemu-system-arm",
"qemu-system-i386-headless",
" qemu-system-i386",
"qemu-system-riscv32-headless",
" qemu-system-riscv32",
"qemu-system-riscv64-headless",
" qemu-system-riscv64",
"qemu-system-x86_64-headless",
" qemu-system-x86_64",
"qemu-user-aarch64",
" qemu-aarch64",
"qemu-user-arm",
" qemu-arm",
"qemu-user-i386",
" qemu-i386",
"qemu-user-riscv32",
" qemu-riscv32",
"qemu-user-riscv64",
" qemu-riscv64",
"qemu-user-x86_64",
" qemu-x86_64",
"qemu-utils",
" qemu-img",
" qemu-io",
" qemu-nbd",
"racket",
" racket",
" raco",
"surfraw",
" opensearch-discover",
" opensearch-genquery",
" sr",
" surfraw",
" surfraw-update-path",
"tcc",
" tcc",
"telegram-cli",
" telegram-cli",
"texlive-installer",
" termux-install-tl",
" termux-patch-texlive",
"yara",
" yara",
" yarac",
"zeronet",
" zeronet",
