"arqiver",
" arqiver",
"aterm",
" aterm",
" xterm",
"audacious",
" audacious",
" audtool",
"azpainter",
" azpainter",
"bochs",
" bochs",
" bxhub",
" bximage",
"bspwm",
" bspc",
" bspwm",
"chocolate-doom",
" chocolate-doom",
" chocolate-doom-setup",
" chocolate-heretic",
" chocolate-heretic-setup",
" chocolate-hexen",
" chocolate-hexen-setup",
" chocolate-server",
" chocolate-strife",
" chocolate-strife-setup",
"dbus-glib",
" dbus-binding-tool",
"dconf",
" dconf",
"debpac",
" debpac",
"desktop-file-utils",
" desktop-file-edit",
" desktop-file-install",
" desktop-file-validate",
" update-desktop-database",
"devilspie",
" devilspie",
"dmenu",
" dmenu",
" dmenu_path",
" dmenu_run",
" stest",
"dosbox",
" dosbox",
"dwm",
" dwm",
"emacs-x",
" ebrowse",
" emacs",
" emacs-27.2",
" emacsclient",
" etags",
"exo",
" exo-desktop-item-edit",
" exo-open",
"feathernotes",
" feathernotes",
"featherpad",
" featherpad",
" fpad",
"feh",
" feh",
"florence",
" florence",
"fltk",
" fltk-config",
" fluid",
"fltk-editor",
" fltk-editor",
"fluxbox",
" fbrun",
" fbsetbg",
" fbsetroot",
" fluxbox",
" fluxbox-generate_menu",
" fluxbox-remote",
" fluxbox-update_configs",
" startfluxbox",
"fvwm",
" FvwmCommand",
" fvwm",
" fvwm-bug",
" fvwm-config",
" fvwm-convert-2.6",
" fvwm-menu-desktop",
" fvwm-menu-directory",
" fvwm-menu-headlines",
" fvwm-menu-xlock",
" fvwm-perllib",
" fvwm-root",
" fvwm2",
" xpmroot",
"galculator",
" galculator",
"geany",
" geany",
"gigolo",
" gigolo",
"glade",
" glade",
" glade-previewer",
"gpg-crypter",
" gpg-crypter",
"gtk-doc",
" gtkdoc-check",
" gtkdoc-depscan",
" gtkdoc-fixxref",
" gtkdoc-mkdb",
" gtkdoc-mkhtml",
" gtkdoc-mkhtml2",
" gtkdoc-mkman",
" gtkdoc-mkpdf",
" gtkdoc-rebase",
" gtkdoc-scan",
" gtkdoc-scangobj",
" gtkdocize",
"gtk-update-icon-cache",
" gtk-update-icon-cache",
"gtk2",
" gtk-builder-convert",
" gtk-demo",
" gtk-query-immodules-2.0",
"gtk3",
" gtk-builder-tool",
" gtk-encode-symbolic-svg",
" gtk-launch",
" gtk-query-immodules-3.0",
" gtk-query-settings",
" gtk3-demo",
" gtk3-demo-application",
" gtk3-icon-browser",
" gtk3-widget-factory",
"gtk4",
" gtk4-builder-tool",
" gtk4-encode-symbolic-svg",
" gtk4-launch",
" gtk4-query-settings",
" gtk4-update-icon-cache",
"gtkwave",
" evcd2vcd",
" fst2vcd",
" fstminer",
" gtkwave",
" lxt2miner",
" lxt2vcd",
" rtlbrowse",
" shmidcat",
" twinwave",
" vcd2fst",
" vcd2lxt",
" vcd2lxt2",
" vcd2vzt",
" vzt2vcd",
" vztminer",
" xml2stems",
"hexchat",
" hexchat",
" hexchat-text",
"i3",
" i3",
" i3-config-wizard",
" i3-dmenu-desktop",
" i3-dump-log",
" i3-input",
" i3-migrate-config-to-v4",
" i3-msg",
" i3-nagbar",
" i3-save-tree",
" i3-sensible-editor",
" i3-sensible-pager",
" i3-sensible-terminal",
" i3-with-shmlog",
" i3bar",
"i3status",
" i3status",
"kconfig",
" kreadconfig5",
" kwriteconfig5",
"kcoreaddons",
" desktoptojson",
"keepassxc",
" keepassxc",
" keepassxc-cli",
"kvantum",
" kvantummanager",
" kvantumpreview",
"l3afpad",
" l3afpad",
"leafpad",
" leafpad",
"libart-lgpl",
" libart2-config",
"libcanberra",
" canberra-gtk-play",
"libfm",
" libfm-pref-apps",
" lxshortcut",
"libglade",
" libglade-convert",
"libnotify",
" notify-send",
"libqtxdg",
" qtxdg-mat",
"libvte",
" vte-2.91",
"libwayland",
" wayland-scanner",
"libwnck",
" wnck-urgency-monitor",
" wnckprop",
"libxfce4ui",
" xfce4-about",
"libxfce4util",
" xfce4-kiosk-query",
"libxkbcommon",
" xkbcli",
"libxpm",
" cxpm",
" sxpm",
"loqui",
" loqui",
"lxappearance",
" lxappearance",
"lximage-qt",
" lximage-qt",
"lxqt-about",
" lxqt-about",
"lxqt-archiver",
" lxqt-archiver",
"lxqt-build-tools",
" lxqt-transupdate",
"lxqt-config",
" lxqt-config",
" lxqt-config-appearance",
" lxqt-config-brightness",
" lxqt-config-file-associations",
" lxqt-config-locale",
"lxqt-globalkeys",
" lxqt-config-globalkeyshortcuts",
" lxqt-globalkeysd",
"lxqt-notificationd",
" lxqt-config-notificationd",
" lxqt-notificationd",
"lxqt-openssh-askpass",
" lxqt-openssh-askpass",
"lxqt-panel",
" lxqt-panel",
"lxqt-runner",
" lxqt-runner",
"lxqt-session",
" lxqt-config-session",
" lxqt-leave",
" lxqt-session",
" startlxqt",
"lxtask",
" lxtask",
"lyx",
" lyx",
" lyxclient",
" tex2lyx",
"marco",
" marco",
" marco-message",
" marco-theme-viewer",
" marco-window-demo",
"matchbox-keyboard",
" matchbox-keyboard",
"mate-desktop",
" mate-about",
" mate-color-select",
"mate-panel",
" mate-desktop-item-edit",
" mate-panel",
" mate-panel-test-applets",
"mate-session-manager",
" mate-session",
" mate-session-inhibit",
" mate-session-properties",
" mate-session-save",
" mate-wm",
"mate-terminal",
" mate-terminal",
" mate-terminal.wrapper",
"mesa-demos",
" arbfplight",
" arbfslight",
" arbocclude",
" arbocclude2",
" array",
" bezier",
" bitmap",
" blinking-teapot",
" bounce",
" brick",
" bump",
" clear-color",
" clear-fbo",
" clear-fbo-scissor",
" clear-fbo-tex",
" clear-random",
" clear-repeat",
" clear-scissor",
" clear-undefined",
" clearspd",
" convolutions",
" copypix",
" copytex",
" createwin",
" cubemap",
" cuberender",
" deriv",
" dinoshade",
" dissolve",
" dlist-begin-call-end",
" dlist-dangling",
" dlist-degenerate",
" dlist-edgeflag",
" dlist-edgeflag-dangling",
" dlist-flat-tri",
" dlist-mat-tri",
" dlist-recursive-call",
" dlist-tri-flat-tri",
" dlist-tri-mat-tri",
" draw2arrays",
" drawarrays",
" drawelements",
" drawelements-large",
" drawoverhead",
" drawpix",
" drawrange",
" engine",
" fbo_firecube",
" fbobind",
" fbotexture",
" fill",
" fire",
" flat-clip",
" fogcoord",
" fplight",
" fragcoord",
" fs-tri",
" fslight",
" fsraytrace",
" gamma",
" gearbox",
" gears",
" geartrain",
" genmipmap",
" geom-outlining-130",
" geom-outlining-150",
" geom-sprites",
" geom-stipple-lines",
" geom-wide-lines",
" glinfo",
" gloss",
" glsl-compile-time",
" glslstateschange",
" glsync",
" gltestperf",
" glthreads",
" glxcontexts",
" glxdemo",
" glxgears",
" glxgears_fbconfig",
" glxgears_pixmap",
" glxheads",
" glxinfo",
" glxpbdemo",
" glxpixmap",
" glxsnoop",
" glxswapcontrol",
" gs-tri",
" gsraytrace",
" identity",
" ipers",
" isosurf",
" line",
" line-clip",
" line-cull",
" line-flat",
" line-smooth",
" line-stipple-wide",
" line-userclip",
" line-userclip-clip",
" line-userclip-nop",
" line-userclip-nop-clip",
" line-wide",
" line-xor",
" lineloop",
" lineloop-clip",
" lineloop-elts",
" linestrip",
" linestrip-clip",
" linestrip-flat-stipple",
" linestrip-stipple",
" linestrip-stipple-wide",
" linktest",
" lodbias",
" long-fixed-func",
" mandelbrot",
" manywin",
" morph3d",
" multiarb",
" multictx",
" multinoise",
" multitex",
" noise",
" noise2",
" offset",
" overlay",
" paltex",
" pbdemo",
" pbinfo",
" pgon-mode",
" pixeltest",
" point",
" point-clip",
" point-param",
" point-sprite",
" point-wide",
" point-wide-smooth",
" pointblast",
" pointcoord",
" points",
" poly",
" poly-flat",
" poly-flat-clip",
" poly-flat-unfilled-clip",
" poly-unfilled",
" projtex",
" quad",
" quad-clip",
" quad-clip-all-vertices",
" quad-clip-nearplane",
" quad-degenerate",
" quad-flat",
" quad-offset-factor",
" quad-offset-unfilled",
" quad-offset-units",
" quad-tex-2d",
" quad-tex-3d",
" quad-tex-alpha",
" quad-tex-pbo",
" quad-tex-sub",
" quad-unfilled",
" quad-unfilled-clip",
" quad-unfilled-stipple",
" quads",
" quadstrip",
" quadstrip-clip",
" quadstrip-cont",
" quadstrip-flat",
" ray",
" readpix",
" readpixels",
" reflect",
" renormal",
" samplers",
" samplers_array",
" shadow_sampler",
" shadowtex",
" shape",
" sharedtex",
" sharedtex_mt",
" shtest",
" simplex-noise",
" singlebuffer",
" skinning",
" spectex",
" spriteblast",
" stex3d",
" sub-tex",
" swapbuffers",
" teapot",
" terrain",
" tessdemo",
" tex-quads",
" texaaline",
" texcyl",
" texdemo1",
" texenv",
" teximage",
" texture_from_pixmap",
" textures",
" toyball",
" tri",
" tri-2101010",
" tri-2101010-dlist",
" tri-alpha",
" tri-alpha-tex",
" tri-array-interleaved",
" tri-blend",
" tri-blend-color",
" tri-blend-max",
" tri-blend-min",
" tri-blend-revsub",
" tri-blend-sub",
" tri-clear",
" tri-clip",
" tri-cull",
" tri-cull-both",
" tri-dlist",
" tri-edgeflag",
" tri-edgeflag-array",
" tri-edgeflag-pv",
" tri-fbo",
" tri-fbo-tex",
" tri-fbo-tex-mip",
" tri-flat",
" tri-flat-clip",
" tri-fog",
" tri-fp",
" tri-fp-const-imm",
" tri-lit",
" tri-lit-material",
" tri-logicop-none",
" tri-logicop-xor",
" tri-mask-tri",
" tri-multitex-vbo",
" tri-orig",
" tri-point-line-clipped",
" tri-query",
" tri-repeat",
" tri-rotate",
" tri-scissor-tri",
" tri-square",
" tri-stencil",
" tri-stipple",
" tri-tex",
" tri-tex-1d",
" tri-tex-3d",
" tri-tex-stipple",
" tri-tri",
" tri-unfilled",
" tri-unfilled-clip",
" tri-unfilled-edgeflag",
" tri-unfilled-fog",
" tri-unfilled-point",
" tri-unfilled-smooth",
" tri-unfilled-tri",
" tri-unfilled-tri-lit",
" tri-unfilled-userclip",
" tri-unfilled-userclip-stip",
" tri-userclip",
" tri-viewport",
" tri-z",
" tri-z-9",
" tri-z-clip",
" tri-z-eq",
" trifan",
" trifan-flat",
" trifan-flat-clip",
" trifan-flat-unfilled-clip",
" trifan-unfilled",
" trirast",
" trispd",
" tristrip",
" tristrip-clip",
" tristrip-flat",
" tunnel",
" tunnel2",
" twoside",
" vao_demo",
" vbo",
" vbo-drawarrays",
" vbo-drawarrays-2101010",
" vbo-drawelements",
" vbo-drawrange",
" vbo-noninterleaved",
" vbo-tri",
" vert-or-frag-only",
" vert-tex",
" vertexrate",
" vp-array",
" vp-array-hf",
" vp-array-int",
" vp-clip",
" vp-line-clip",
" vp-tri",
" vp-tri-cb",
" vp-tri-cb-pos",
" vp-tri-cb-tex",
" vp-tri-imm",
" vp-tri-invariant",
" vp-tri-swap",
" vp-tri-tex",
" vp-unfilled",
" vsraytrace",
" wincopy",
" winpos",
" xfont",
" xrotfontdemo",
"mpv-x",
" mpv",
"mtpaint",
" mtpaint",
"netsurf",
" netsurf",
" netsurf-gtk3",
"nxengine",
" nx",
"obconf",
" obconf",
"obconf-qt",
" obconf-qt",
"openbox",
" obxprop",
" openbox",
" openbox-session",
"openttd",
" openttd",
"otter-browser",
" otter-browser",
"pavucontrol-qt",
" pavucontrol-qt",
"pcmanfm",
" pcmanfm",
"pcmanfm-qt",
" pcmanfm-qt",
"pidgin",
" pidgin",
"pinentry-gtk",
" pinentry",
" pinentry-curses",
" pinentry-gtk-2",
"plotutils",
" double",
" graph",
" hersheydemo",
" ode",
" plot",
" plotfont",
" spline",
" tek2plot",
"polybar",
" polybar",
" polybar-msg",
"putty",
" pageant",
" plink",
" pscp",
" psftp",
" psusan",
" pterm",
" putty",
" puttygen",
" puttytel",
"pypanel",
" pypanel",
"qemu-system-aarch64",
" qemu-system-aarch64",
"qemu-system-arm",
" qemu-system-arm",
"qemu-system-i386",
" qemu-system-i386",
"qemu-system-ppc",
" qemu-system-ppc",
"qemu-system-ppc64",
" qemu-system-ppc64",
"qemu-system-riscv32",
" qemu-system-riscv32",
"qemu-system-riscv64",
" qemu-system-riscv64",
"qemu-system-x86-64",
" qemu-system-x86_64",
"qemu-system-x86_64",
" qemu-system-x86_64",
"qemu-utils",
" qemu-img",
" qemu-io",
" qemu-nbd",
"qgit",
" qgit",
"qt-creator",
" qtcreator",
"qt5-declarative-dev",
" qml",
" qmlcachegen",
" qmlimportscanner",
" qmllint",
" qmlmin",
" qmlscene",
" qmltestrunner",
"qt5-qtbase",
" moc",
" qdbuscpp2xml",
" qdbusxml2cpp",
" qlalr",
" qmake",
" qvkgen",
" rcc",
" uic",
"qt5-qtdeclarative",
" qml",
" qmlcachegen",
" qmlimportscanner",
" qmllint",
" qmlmin",
" qmlpreview",
" qmlscene",
" qmltestrunner",
"qt5-qttools",
" assistant",
" designer",
" lconvert",
" linguist",
" lrelease",
" lupdate",
" makeqpf",
" pixeltool",
" qcollectiongenerator",
" qdbus",
" qdbusviewer",
" qdistancefieldgenerator",
" qev",
" qhelpgenerator",
" qtattributionsscanner",
" qtdiag",
" qtpaths",
" qtplugininfo",
"qt5-qtxmlpatterns",
" xmlpatterns",
" xmlpatternsvalidator",
"qt5-tools",
" lconvert",
" lrelease",
" lupdate",
" qtattributionsscanner",
" qtdiag",
" qtpaths",
" qtplugininfo",
"qt5ct",
" qt5ct",
"qterminal",
" qterminal",
"recordmydesktop",
" recordmydesktop",
"ristretto",
" ristretto",
"rofi",
" rofi",
" rofi-sensible-terminal",
" rofi-theme-selector",
"roxterm",
" roxterm",
" roxterm-config",
"scrot",
" scrot",
"sdl",
" sdl-config",
"sdl2",
" sdl2-config",
"shared-mime-info",
" update-mime-database",
"st",
" st",
"sxhkd",
" sxhkd",
"termux-x11",
" termux-x11",
"the-powder-toy",
" powder",
" the-powder-toy",
"thunar",
" Thunar",
" thunar",
" thunar-settings",
"tigervnc",
" Xvnc",
" vncconfig",
" vncpasswd",
" vncserver",
" x0vncserver",
"tigervnc-viewer",
" vncviewer",
"tilda",
" tilda",
"tint2",
" tint2",
" tint2conf",
"transmission-gtk",
" transmission-cli",
" transmission-create",
" transmission-daemon",
" transmission-edit",
" transmission-gtk",
" transmission-remote",
" transmission-show",
"uget",
" uget",
" uget-gtk",
" uget-gtk-1to2",
"vim-gtk",
" eview",
" evim",
" ex",
" gview",
" gvim",
" gvimdiff",
" gvimtutor",
" rgview",
" rgvim",
" rview",
" rvim",
" vi",
" view",
" vim",
" vimdiff",
" vimtutor",
" xxd",
"webkit2gtk",
" WebKitWebDriver",
"wireshark-gtk",
" capinfos",
" captype",
" dumpcap",
" editcap",
" idl2wrs",
" mergecap",
" mmdbresolve",
" randpkt",
" rawshark",
" reordercap",
" sharkd",
" text2pcap",
" tshark",
" wireshark-gtk",
"wmaker",
" WPrefs",
" convertfonts",
" geticonset",
" getstyle",
" seticons",
" setstyle",
" wdread",
" wdwrite",
" wkdemenu.pl",
" wm-oldmenu2new",
" wmagnify",
" wmaker",
" wmaker.inst",
" wmgenmenu",
" wmiv",
" wmmenugen",
" wmsetbg",
" wxcopy",
" wxpaste",
"x11vnc",
" Xdummy",
" x11vnc",
"x2x",
" x2x",
"xarchiver",
" xarchiver",
"xcompmgr",
" xcompmgr",
"xfce4-appfinder",
" xfce4-appfinder",
" xfrun4",
"xfce4-clipman-plugin",
" xfce4-clipman",
" xfce4-clipman-history",
" xfce4-clipman-settings",
" xfce4-popup-clipman",
" xfce4-popup-clipman-actions",
"xfce4-panel",
" xfce4-panel",
" xfce4-popup-applicationsmenu",
" xfce4-popup-directorymenu",
" xfce4-popup-windowmenu",
"xfce4-panel-profiles",
" xfce4-panel-profiles",
"xfce4-session",
" startxfce4",
" xfce4-session",
" xfce4-session-logout",
" xfce4-session-settings",
" xflock4",
"xfce4-settings",
" xfce4-accessibility-settings",
" xfce4-appearance-settings",
" xfce4-display-settings",
" xfce4-find-cursor",
" xfce4-keyboard-settings",
" xfce4-mime-helper",
" xfce4-mime-settings",
" xfce4-mouse-settings",
" xfce4-settings-editor",
" xfce4-settings-manager",
" xfsettingsd",
"xfce4-taskmanager",
" xfce4-taskmanager",
"xfce4-terminal",
" xfce4-terminal",
"xfce4-whiskermenu-plugin",
" xfce4-popup-whiskermenu",
"xfconf",
" xfconf-query",
"xfdesktop",
" xfdesktop",
" xfdesktop-settings",
"xfwm4",
" xfwm4",
" xfwm4-settings",
" xfwm4-tweaks-settings",
" xfwm4-workspace-settings",
"xorg-font-util",
" bdftruncate",
" ucs2any",
"xorg-iceauth",
" iceauth",
"xorg-luit",
" luit",
"xorg-mkfontscale",
" mkfontdir",
" mkfontscale",
"xorg-server",
" X",
" Xorg",
"xorg-server-xvfb",
" Xvfb",
"xorg-twm",
" twm",
"xorg-xauth",
" xauth",
"xorg-xcalc",
" xcalc",
"xorg-xclock",
" xclock",
"xorg-xdpyinfo",
" xdpyinfo",
"xorg-xev",
" xev",
"xorg-xhost",
" xhost",
"xorg-xkbcomp",
" xkbcomp",
"xorg-xlsfonts",
" xlsfonts",
"xorg-xmessage",
" xmessage",
"xorg-xprop",
" xprop",
"xorg-xrandr",
" xkeystone",
" xrandr",
"xorg-xrdb",
" xrdb",
"xorg-xsetroot",
" xsetroot",
"xorg-xwininfo",
" xwininfo",
"xournal",
" xournal",
"xpdf",
" pdfdetach",
" pdffonts",
" pdfimages",
" pdfinfo",
" pdftohtml",
" pdftopng",
" pdftoppm",
" pdftops",
" pdftotext",
" xpdf",
"xrdp",
" xrdp",
" xrdp-chansrv",
" xrdp-dis",
" xrdp-genkeymap",
" xrdp-keygen",
" xrdp-sesadmin",
" xrdp-sesman",
" xrdp-sesrun",
"xsel",
" xsel",
"xwayland",
" Xwayland",
"zenity",
" gdialog",
" zenity",
