"arqiver",
" arqiver",
"aterm",
" aterm",
" xterm",
"audacious",
" audacious",
" audtool",
"azpainter",
" azpainter",
"bochs",
" bochs",
" bxhub",
" bximage",
"bspwm",
" bspc",
" bspwm",
"chocolate-doom",
" chocolate-doom",
" chocolate-doom-setup",
" chocolate-heretic",
" chocolate-heretic-setup",
" chocolate-hexen",
" chocolate-hexen-setup",
" chocolate-server",
" chocolate-strife",
" chocolate-strife-setup",
"dbus-glib",
" dbus-binding-tool",
"dconf",
" dconf",
"desktop-file-utils",
" desktop-file-edit",
" desktop-file-install",
" desktop-file-validate",
" update-desktop-database",
"dmenu",
" dmenu",
" dmenu_path",
" dmenu_run",
" stest",
"dosbox",
" dosbox",
"dwm",
" dwm",
"exo",
" exo-desktop-item-edit",
" exo-open",
"feathernotes",
" feathernotes",
"featherpad",
" featherpad",
" fpad",
"feh",
" feh",
"florence",
" florence",
"fltk",
" fltk-config",
" fluid",
"fltk-editor",
" fltk-editor",
"fluxbox",
" fbrun",
" fbsetbg",
" fbsetroot",
" fluxbox",
" fluxbox-generate_menu",
" fluxbox-remote",
" fluxbox-update_configs",
" startfluxbox",
"fvwm",
" FvwmCommand",
" fvwm",
" fvwm-bug",
" fvwm-config",
" fvwm-convert-2.6",
" fvwm-menu-desktop",
" fvwm-menu-directory",
" fvwm-menu-headlines",
" fvwm-menu-xlock",
" fvwm-perllib",
" fvwm-root",
" fvwm2",
" xpmroot",
"galculator",
" galculator",
"geany",
" geany",
"gigolo",
" gigolo",
"gpg-crypter",
" gpg-crypter",
"gtk-doc",
" gtkdoc-check",
" gtkdoc-depscan",
" gtkdoc-fixxref",
" gtkdoc-mkdb",
" gtkdoc-mkhtml",
" gtkdoc-mkhtml2",
" gtkdoc-mkman",
" gtkdoc-mkpdf",
" gtkdoc-rebase",
" gtkdoc-scan",
" gtkdoc-scangobj",
" gtkdocize",
"gtk-update-icon-cache",
" gtk-update-icon-cache",
"gtk2",
" gtk-builder-convert",
" gtk-demo",
" gtk-query-immodules-2.0",
"gtk3",
" gtk-builder-tool",
" gtk-encode-symbolic-svg",
" gtk-launch",
" gtk-query-immodules-3.0",
" gtk-query-settings",
" gtk3-demo",
" gtk3-demo-application",
" gtk3-icon-browser",
" gtk3-widget-factory",
"gtk4",
" gtk4-builder-tool",
" gtk4-encode-symbolic-svg",
" gtk4-launch",
" gtk4-query-settings",
" gtk4-update-icon-cache",
"gtkwave",
" evcd2vcd",
" fst2vcd",
" fstminer",
" ghwdump",
" gtkwave",
" lxt2miner",
" lxt2vcd",
" rtlbrowse",
" shmidcat",
" twinwave",
" vcd2fst",
" vcd2lxt",
" vcd2lxt2",
" vcd2vzt",
" vzt2vcd",
" vztminer",
" xml2stems",
"hexchat",
" hexchat",
" hexchat-text",
"i3",
" i3",
" i3-config-wizard",
" i3-dmenu-desktop",
" i3-dump-log",
" i3-input",
" i3-migrate-config-to-v4",
" i3-msg",
" i3-nagbar",
" i3-save-tree",
" i3-sensible-editor",
" i3-sensible-pager",
" i3-sensible-terminal",
" i3-with-shmlog",
" i3bar",
"i3status",
" i3status",
"kconfig",
" kreadconfig5",
" kwriteconfig5",
"kcoreaddons",
" desktoptojson",
"keepassxc",
" keepassxc",
" keepassxc-cli",
"kvantum",
" kvantummanager",
" kvantumpreview",
"l3afpad",
" l3afpad",
"leafpad",
" leafpad",
"libart-lgpl",
" libart2-config",
"libcanberra",
" canberra-gtk-play",
"libfm",
" libfm-pref-apps",
" lxshortcut",
"libglade",
" libglade-convert",
"libnotify",
" notify-send",
"libqtxdg",
" qtxdg-mat",
"libvte",
" vte-2.91",
"libwnck",
" wnck-urgency-monitor",
" wnckprop",
"libxfce4ui",
" xfce4-about",
"libxfce4util",
" xfce4-kiosk-query",
"libxkbcommon",
" xkbcli",
"libxpm",
" cxpm",
" sxpm",
"loqui",
" loqui",
"lxappearance",
" lxappearance",
"lximage-qt",
" lximage-qt",
"lxqt-about",
" lxqt-about",
"lxqt-archiver",
" lxqt-archiver",
"lxqt-build-tools",
" lxqt-transupdate",
"lxqt-config",
" lxqt-config",
" lxqt-config-appearance",
" lxqt-config-brightness",
" lxqt-config-file-associations",
" lxqt-config-locale",
"lxqt-globalkeys",
" lxqt-config-globalkeyshortcuts",
" lxqt-globalkeysd",
"lxqt-notificationd",
" lxqt-config-notificationd",
" lxqt-notificationd",
"lxqt-openssh-askpass",
" lxqt-openssh-askpass",
"lxqt-panel",
" lxqt-panel",
"lxqt-runner",
" lxqt-runner",
"lxqt-session",
" lxqt-config-session",
" lxqt-leave",
" lxqt-session",
" startlxqt",
"lxtask",
" lxtask",
"lyx",
" lyx",
" lyxclient",
" tex2lyx",
"marco",
" marco",
" marco-message",
" marco-theme-viewer",
" marco-window-demo",
"matchbox-keyboard",
" matchbox-keyboard",
"mate-desktop",
" mate-about",
" mate-color-select",
"mate-panel",
" mate-desktop-item-edit",
" mate-panel",
" mate-panel-test-applets",
"mate-session-manager",
" mate-session",
" mate-session-inhibit",
" mate-session-properties",
" mate-session-save",
" mate-wm",
"mate-terminal",
" mate-terminal",
" mate-terminal.wrapper",
"mpv-x",
" mpv",
"mtpaint",
" mtpaint",
"netsurf",
" netsurf",
" netsurf-gtk3",
"obconf",
" obconf",
"obconf-qt",
" obconf-qt",
"openbox",
" obxprop",
" openbox",
" openbox-session",
"openttd",
" openttd",
"otter-browser",
" otter-browser",
"pavucontrol-qt",
" pavucontrol-qt",
"pcmanfm",
" pcmanfm",
"pcmanfm-qt",
" pcmanfm-qt",
"pidgin",
" pidgin",
"pinentry-gtk",
" pinentry",
" pinentry-curses",
" pinentry-gtk-2",
"plotutils",
" double",
" graph",
" hersheydemo",
" ode",
" plot",
" plotfont",
" spline",
" tek2plot",
"polybar",
" polybar",
" polybar-msg",
"putty",
" pageant",
" plink",
" pscp",
" psftp",
" pterm",
" putty",
" puttygen",
" puttytel",
"pypanel",
" pypanel",
"qemu-system-aarch64",
" qemu-system-aarch64",
"qemu-system-arm",
" qemu-system-arm",
"qemu-system-i386",
" qemu-system-i386",
"qemu-system-riscv32",
" qemu-system-riscv32",
"qemu-system-riscv64",
" qemu-system-riscv64",
"qemu-system-x86",
" qemu-keymap",
" qemu-system-x86_64",
"qemu-system-x86-64",
" qemu-system-x86_64",
"qemu-utils",
" qemu-img",
" qemu-io",
" qemu-nbd",
"qgit",
" qgit",
"qt-creator",
" qtcreator",
"qt5-declarative",
" qml",
" qmlcachegen",
" qmlimportscanner",
" qmllint",
" qmlmin",
" qmlscene",
" qmltestrunner",
"qt5-declarative-dev",
" qml",
" qmlcachegen",
" qmlimportscanner",
" qmllint",
" qmlmin",
" qmlscene",
" qmltestrunner",
"qt5-qtbase",
" moc",
" qdbuscpp2xml",
" qdbusxml2cpp",
" qlalr",
" qmake",
" qvkgen",
" rcc",
" uic",
"qt5-qtdeclarative",
" qml",
" qmlcachegen",
" qmlimportscanner",
" qmllint",
" qmlmin",
" qmlpreview",
" qmlscene",
" qmltestrunner",
"qt5-qttools",
" assistant",
" designer",
" lconvert",
" linguist",
" lrelease",
" lupdate",
" makeqpf",
" pixeltool",
" qcollectiongenerator",
" qdbus",
" qdbusviewer",
" qdistancefieldgenerator",
" qev",
" qhelpgenerator",
" qtattributionsscanner",
" qtdiag",
" qtpaths",
" qtplugininfo",
"qt5-qtxmlpatterns",
" xmlpatterns",
" xmlpatternsvalidator",
"qt5-tools",
" lconvert",
" lrelease",
" lupdate",
" qtattributionsscanner",
" qtdiag",
" qtpaths",
" qtplugininfo",
"qterminal",
" qterminal",
"recordmydesktop",
" recordmydesktop",
"ristretto",
" ristretto",
"rofi",
" rofi",
" rofi-sensible-terminal",
" rofi-theme-selector",
"roxterm",
" roxterm",
" roxterm-config",
"sdl",
" sdl-config",
"sdl2",
" sdl2-config",
"shared-mime-info",
" update-mime-database",
"st",
" st",
"sxhkd",
" sxhkd",
"the-powder-toy",
" powder",
" the-powder-toy",
"thunar",
" Thunar",
" thunar",
" thunar-settings",
"tigervnc",
" Xvnc",
" vncconfig",
" vncpasswd",
" vncserver",
" x0vncserver",
"tigervnc-viewer",
" vncviewer",
"transmission-gtk",
" transmission-cli",
" transmission-create",
" transmission-daemon",
" transmission-edit",
" transmission-gtk",
" transmission-remote",
" transmission-show",
"uget",
" uget",
" uget-gtk",
" uget-gtk-1to2",
"vim-gtk",
" eview",
" evim",
" ex",
" gview",
" gvim",
" gvimdiff",
" gvimtutor",
" rgview",
" rgvim",
" rview",
" rvim",
" vi",
" view",
" vim",
" vimdiff",
" vimtutor",
" xxd",
"webkit2gtk",
" WebKitWebDriver",
"wireshark-gtk",
" capinfos",
" captype",
" dumpcap",
" editcap",
" idl2wrs",
" mergecap",
" mmdbresolve",
" randpkt",
" rawshark",
" reordercap",
" sharkd",
" text2pcap",
" tshark",
" wireshark-gtk",
"wmaker",
" WPrefs",
" convertfonts",
" geticonset",
" getstyle",
" seticons",
" setstyle",
" wdread",
" wdwrite",
" wkdemenu.pl",
" wm-oldmenu2new",
" wmagnify",
" wmaker",
" wmaker.inst",
" wmgenmenu",
" wmiv",
" wmmenugen",
" wmsetbg",
" wxcopy",
" wxpaste",
"x11vnc",
" Xdummy",
" x11vnc",
"x2x",
" x2x",
"xarchiver",
" xarchiver",
"xcompmgr",
" xcompmgr",
"xfce4-appfinder",
" xfce4-appfinder",
" xfrun4",
"xfce4-clipman-plugin",
" xfce4-clipman",
" xfce4-clipman-history",
" xfce4-clipman-settings",
" xfce4-popup-clipman",
" xfce4-popup-clipman-actions",
"xfce4-panel",
" xfce4-panel",
" xfce4-popup-applicationsmenu",
" xfce4-popup-directorymenu",
" xfce4-popup-windowmenu",
"xfce4-panel-profiles",
" xfce4-panel-profiles",
"xfce4-session",
" startxfce4",
" xfce4-session",
" xfce4-session-logout",
" xfce4-session-settings",
" xflock4",
"xfce4-settings",
" xfce4-accessibility-settings",
" xfce4-appearance-settings",
" xfce4-display-settings",
" xfce4-find-cursor",
" xfce4-keyboard-settings",
" xfce4-mime-helper",
" xfce4-mime-settings",
" xfce4-mouse-settings",
" xfce4-settings-editor",
" xfce4-settings-manager",
" xfsettingsd",
"xfce4-taskmanager",
" xfce4-taskmanager",
"xfce4-terminal",
" xfce4-terminal",
"xfce4-whiskermenu-plugin",
" xfce4-popup-whiskermenu",
"xfconf",
" xfconf-query",
"xfdesktop",
" xfdesktop",
" xfdesktop-settings",
"xfwm4",
" xfwm4",
" xfwm4-settings",
" xfwm4-tweaks-settings",
" xfwm4-workspace-settings",
"xorg-font-util",
" bdftruncate",
" ucs2any",
"xorg-iceauth",
" iceauth",
"xorg-luit",
" luit",
"xorg-mkfontscale",
" mkfontdir",
" mkfontscale",
"xorg-server",
" X",
" Xorg",
"xorg-server-xvfb",
" Xvfb",
"xorg-twm",
" twm",
"xorg-xauth",
" xauth",
"xorg-xcalc",
" xcalc",
"xorg-xclock",
" xclock",
"xorg-xdpyinfo",
" xdpyinfo",
"xorg-xev",
" xev",
"xorg-xhost",
" xhost",
"xorg-xkbcomp",
" xkbcomp",
"xorg-xlsfonts",
" xlsfonts",
"xorg-xmessage",
" xmessage",
"xorg-xrandr",
" xkeystone",
" xrandr",
"xorg-xrdb",
" xrdb",
"xorg-xsetroot",
" xsetroot",
"xournal",
" xournal",
"xpdf",
" pdfdetach",
" pdffonts",
" pdfimages",
" pdfinfo",
" pdftohtml",
" pdftopng",
" pdftoppm",
" pdftops",
" pdftotext",
" xpdf",
"xrdp",
" xrdp",
" xrdp-chansrv",
" xrdp-dis",
" xrdp-genkeymap",
" xrdp-keygen",
" xrdp-sesadmin",
" xrdp-sesman",
" xrdp-sesrun",
"xsel",
" xsel",
"zenity",
" gdialog",
" zenity",
